# Generated by Django 3.1.5 on 2021-01-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(default='', max_length=20)),
                ('date', models.DateField()),
                ('fed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
