# Generated by Django 3.1.5 on 2021-01-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='treats',
            field=models.IntegerField(default=1),
        ),
    ]
