# Generated by Django 3.1.5 on 2021-01-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210119_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='comment',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='meal_type',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
