# Generated by Django 3.1.5 on 2021-01-25 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='pack_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.pack'),
            preserve_default=False,
        ),
    ]
