# Generated by Django 3.1.5 on 2021-01-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_food_pack_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='pack_id',
            new_name='pack',
        ),
    ]
